apiVersion: v1
kind: Service
metadata:
  name: service-module-es
  namespace: duck-pre
  labels:
    admin: admin-enabled
spec:
  selector:
    app: service-module-es
  ports:
    - port: 8185
      protocol: TCP
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-module-es
  namespace: duck-pre
  labels:
    app: service-module-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-module-es
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      name: service-module-es
      namespace: duck-pre
      labels:
        app: service-module-es
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: service-module-es
          image: harbor.zhuiyinanian.cn/app-pre/es-service:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
            - name: logs
              mountPath: /tmp/logs/services/es
          env:
            - name: JAVA_OPTS
              value: -Duser.timezone=Asia/Shanghai file.encoding=utf-8
          livenessProbe:
            httpGet:
              port: 8185
              path: /actuator/info
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              port: 8185
              path: /actuator/info
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.0.0
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          securityContext:
            runAsUser: 0
          resources:
            limits:
              cpu: 50m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
            - name: filebeat-config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
            - name: logs
              mountPath: /tmp/logs/services/es
      volumes:
        - name: time
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-es-config
      restartPolicy: Always
      serviceAccountName: duck-pre