apiVersion: v1
kind: Service
metadata:
  name: service-module-user
  namespace: duck-pre
  labels:
    admin: admin-enabled
spec:
  selector:
    app: service-module-user
  ports:
    - port: 8180
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-module-user
  namespace: duck-pre
  labels:
    app: service-module-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-module-user
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      name: service-module-user
      namespace: duck-pre
      labels:
        app: service-module-user
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: service-module-user
          image: harbor.zhuiyinanian.cn/app-pre/user-service:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
            - name: logs
              mountPath: /tmp/logs/services/user
          env:
            - name: JAVA_OPTS
              value: -Duser.timezone=Asia/Shanghai file.encoding=utf-8
          livenessProbe:
            httpGet:
              port: 8180
              path: /actuator/info
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              port: 8180
              path: /actuator/info
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.0.0
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          securityContext:
            runAsUser: 0
          resources:
            limits:
              cpu: 50m
              memory: 200Mi
            requests:
              cpu: 40m
              memory: 100Mi
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
            - name: filebeat-config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
            - name: logs
              mountPath: /tmp/logs/services/user
      volumes:
        - name: time
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-user-config
      restartPolicy: Always
      serviceAccountName: duck-pre